server:
  port: 8080

spring:
  application:
    name: agb-server

  datasource:
    url: jdbc:mysql://localhost:3306/agb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 2025@hhq
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 2025@hhq

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis-flex:
  mapper-locations: classpath*:mapper/**/*.xml
